"""init models

Revision ID: 02f48b1b65b1
Revises: f0fc2f77eb7f
Create Date: 2024-09-12 22:44:04.153187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f48b1b65b1'
down_revision: Union[str, None] = 'f0fc2f77eb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.drop_index('external_transaction_model_priority_idx', table_name='external_transaction_model')
    op.create_index(op.f('ix_external_transaction_model_priority'), 'external_transaction_model', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_transaction_model_priority'), table_name='external_transaction_model')
    op.create_index('external_transaction_model_priority_idx', 'external_transaction_model', ['priority'], unique=False)
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
