"""add alias to bank_detail

Revision ID: 0b0592dba5ca
Revises: 9116796c4c72
Create Date: 2025-01-30 11:12:54.398452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0592dba5ca'
down_revision: Union[str, None] = '9116796c4c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('alias', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_detail_model', 'alias')
    # ### end Alembic commands ###
