"""add last_transaction_timestamp to TeamModel

Revision ID: 0f1fab6298ee
Revises: 86014223b5f0
Create Date: 2025-04-14 20:02:30.847174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1fab6298ee'
down_revision: Union[str, None] = '86014223b5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('last_transaction_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'last_transaction_timestamp')
    # ### end Alembic commands ###
