"""upgrade MessageModel offset_id

Revision ID: 175e2a048428
Revises: f10fe20234a0
Create Date: 2025-02-12 20:11:11.450765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175e2a048428'
down_revision: Union[str, None] = 'f10fe20234a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_model', sa.Column('offset_id', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_index(op.f('ix_message_model_offset_id'), 'message_model', ['offset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_model_offset_id'), table_name='message_model')
    op.drop_column('message_model', 'offset_id')
    # ### end Alembic commands ###
