"""appeals callbacks

Revision ID: 21bc9064fe93
Revises: 61eeccaa0f86
Create Date: 2025-04-26 13:14:27.297355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bc9064fe93'
down_revision: Union[str, None] = '61eeccaa0f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('merchant_appeal_id', sa.String(), nullable=True))
    op.add_column('appeals', sa.Column('finalization_callback_uri', sa.String(), nullable=True))
    op.add_column('appeals', sa.Column('ask_statement_callback_uri', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'appeals', ['merchant_appeal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vip_payer_model_id'), table_name='vip_payer_model')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.drop_constraint(None, 'appeals', type_='unique')
    # ### end Alembic commands ###
