"""Add limitation vip and indexes, timestamp to vip_model

Revision ID: 23fba1e30848
Revises: 0309b9814811
Create Date: 2025-03-21 11:19:22.897444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fba1e30848'
down_revision: Union[str, None] = '0309b9814811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bank_detail_model',
        sa.Column('count_vip_payers', sa.BigInteger(), nullable=False, server_default='0')
    )
    op.add_column(
        'bank_detail_model',
        sa.Column('max_vip_payers', sa.BigInteger(), nullable=False, server_default='0')
    )
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.create_index('idx_bank_detail_active_deleted_vip', 'bank_detail_model', ['is_active', 'is_deleted', 'is_vip'], unique=False)
    op.create_index('idx_bank_detail_fiat_range', 'bank_detail_model', ['fiat_min_inbound', 'fiat_max_inbound'], unique=False)
    op.create_index('idx_bank_detail_team_active_deleted', 'bank_detail_model', ['team_id', 'is_deleted', 'is_active'], unique=False)
    op.create_index('idx_bank_detail_vip_payers_limit', 'bank_detail_model', ['count_vip_payers', 'max_vip_payers'], unique=False)
    op.create_index(op.f('ix_bank_detail_model_is_vip'), 'bank_detail_model', ['is_vip'], unique=False)
    op.add_column('vip_payer_model', sa.Column('last_transaction_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('idx_vip_payer_last_tx', 'vip_payer_model', ['last_transaction_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vip_payer_last_tx', table_name='vip_payer_model')
    op.drop_column('vip_payer_model', 'last_transaction_timestamp')
    op.drop_index(op.f('ix_bank_detail_model_is_vip'), table_name='bank_detail_model')
    op.drop_index('idx_bank_detail_vip_payers_limit', table_name='bank_detail_model')
    op.drop_index('idx_bank_detail_team_active_deleted', table_name='bank_detail_model')
    op.drop_index('idx_bank_detail_fiat_range', table_name='bank_detail_model')
    op.drop_index('idx_bank_detail_active_deleted_vip', table_name='bank_detail_model')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.drop_column('bank_detail_model', 'max_vip_payers')
    op.drop_column('bank_detail_model', 'count_vip_payers')
    # ### end Alembic commands ###
