"""table whitelist_payer_id_model and is_whitelist in MerchantModel

Revision ID: 2e919eea7823
Revises: 23fba1e30848
Create Date: 2025-03-26 14:07:35.087452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e919eea7823'
down_revision: Union[str, None] = '23fba1e30848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist_payer_id_model',
    sa.Column('payer_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('payer_id', 'merchant_id')
    )
    op.create_index('idx_whitelist_payer_merchant', 'whitelist_payer_id_model', ['payer_id', 'merchant_id'], unique=False)
    op.add_column('merchants', sa.Column('is_whitelist', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'is_whitelist')
    op.drop_index('idx_whitelist_payer_merchant', table_name='whitelist_payer_id_model')
    op.drop_table('whitelist_payer_id_model')
    # ### end Alembic commands ###
