"""Add time and transaction count limits

Revision ID: 35e00f3da413
Revises: 660b3c1ef935
Create Date: 2025-03-31 13:05:10.546106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e00f3da413'
down_revision: Union[str, None] = '660b3c1ef935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('today_transactions_count', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('bank_detail_model', sa.Column('max_today_transactions_count', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('bank_detail_model', sa.Column('period_start_time', sa.TIME(), nullable=True))
    op.add_column('bank_detail_model', sa.Column('period_finish_time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_detail_model', 'period_finish_time')
    op.drop_column('bank_detail_model', 'period_start_time')
    op.drop_column('bank_detail_model', 'max_today_transactions_count')
    op.drop_column('bank_detail_model', 'today_transactions_count')
    # ### end Alembic commands ###
