"""add last_accept_timestamp

Revision ID: 466862115d16
Revises: b3aa7a0e18a6
Create Date: 2025-06-11 12:08:48.045207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466862115d16'
down_revision: Union[str, None] = 'b3aa7a0e18a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('bank_detail_model', sa.Column(
        'last_accept_timestamp',
        sa.TIMESTAMP(),
        nullable=True
    ))

    op.execute("""
        UPDATE bank_detail_model
        SET last_accept_timestamp = last_transaction_timestamp
    """)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_detail_model', 'last_accept_timestamp')
    # ### end Alembic commands ###
