"""add max_inbound_close_count

Revision ID: 4ba4c33a9503
Revises: d073c686859a
Create Date: 2025-05-27 13:06:44.452712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba4c33a9503'
down_revision: Union[str, None] = 'd073c686859a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_settings', sa.Column('max_inbound_close_count', sa.Integer(), server_default='99', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'max_inbound_close_count')
    # ### end Alembic commands ###
