"""add block_deposit

Revision ID: 592cf6370803
Revises: 96451832ccaf
Create Date: 2025-06-04 10:29:09.986631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592cf6370803'
down_revision: Union[str, None] = '96451832ccaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_settings', sa.Column('block_deposit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'block_deposit')
    # ### end Alembic commands ###
