"""add auto close outbound

Revision ID: 5fc59e2cc272
Revises: a84cd2b80173
Create Date: 2025-06-24 13:57:40.123635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fc59e2cc272'
down_revision: Union[str, None] = 'a84cd2b80173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_settings', sa.Column('auto_close_outbound_transactions_s', sa.Integer(), server_default='1800', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'auto_close_outbound_transactions_s')
    # ### end Alembic commands ###
