"""add max hold to geo_settings and ext_model

Revision ID: 61eeccaa0f86
Revises: cbc7a0f76a09
Create Date: 2025-04-25 14:08:22.289850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61eeccaa0f86'
down_revision: Union[str, None] = 'cbc7a0f76a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_transaction_model', sa.Column('count_hold', sa.Integer(), server_default='0', nullable=False))
    op.add_column('geo_settings', sa.Column('max_count_hold', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'max_count_hold')
    op.drop_column('external_transaction_model', 'count_hold')
    # ### end Alembic commands ###
