"""appeals

Revision ID: 63c9a40c7a55
Revises: cf46f56b9b92
Create Date: 2024-11-25 23:13:49.649843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63c9a40c7a55'
down_revision: Union[str, None] = 'cf46f56b9b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('create_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('receipts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('merchant_statements', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('team_statements', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_merchant_statement_required', sa.Boolean(), nullable=False),
    sa.Column('is_team_statement_required', sa.Boolean(), nullable=False),
    sa.Column('is_support_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('reject_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['external_transaction_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=True)
    op.drop_index('ix_appeal_model_create_timestamp', table_name='appeal_model')
    op.drop_index('ix_appeal_model_id', table_name='appeal_model')
    op.drop_index('ix_appeal_model_offset_id', table_name='appeal_model')
    op.drop_table('appeal_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeal_model',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('offset_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invoice_file_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('create_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['external_transaction_model.id'], name='appeal_model_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'offset_id', name='appeal_model_pkey')
    )
    op.create_index('ix_appeal_model_offset_id', 'appeal_model', ['offset_id'], unique=False)
    op.create_index('ix_appeal_model_id', 'appeal_model', ['id'], unique=True)
    op.create_index('ix_appeal_model_create_timestamp', 'appeal_model', ['create_timestamp'], unique=False)
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
