"""add view_sms_hub

Revision ID: 6505643ddb64
Revises: 175e2a048428
Create Date: 2025-03-03 09:38:58.319731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6505643ddb64'
down_revision: Union[str, None] = '175e2a048428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_matrix', sa.Column('view_sms_hub', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_matrix', 'view_sms_hub')
    # ### end Alembic commands ###
