"""access_matrix

Revision ID: 65d7eef9644f
Revises: ac7e0f3791e3
Create Date: 2024-08-05 23:01:25.313242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '65d7eef9644f'
down_revision: Union[str, None] = 'ac7e0f3791e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_matrix',
                    sa.Column('user_id', sa.String(length=64), nullable=False),
                    sa.Column('view_traffic', sa.Boolean(), nullable=False),
                    sa.Column('view_fee', sa.Boolean(), nullable=False),
                    sa.Column('view_pay_in', sa.Boolean(), nullable=False),
                    sa.Column('view_pay_out', sa.Boolean(), nullable=False),
                    sa.Column('view_supports', sa.Boolean(), nullable=False),
                    sa.Column('view_wallet', sa.Boolean(), nullable=False),
                    sa.Column('view_agents', sa.Boolean(), nullable=False),
                    sa.Column('view_merchants', sa.Boolean(), nullable=False),
                    sa.Column('view_teams', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_matrix')
    # ### end Alembic commands ###
