"""add view_accounting

Revision ID: 6baeae734e26
Revises: 6505643ddb64
Create Date: 2025-03-03 13:10:20.984085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baeae734e26'
down_revision: Union[str, None] = '6505643ddb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_matrix', sa.Column('view_accounting', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_matrix', 'view_accounting')
    # ### end Alembic commands ###
