"""add last disable

Revision ID: 6fa4099c5d40
Revises: c419a74357fe
Create Date: 2025-05-27 15:00:25.336370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa4099c5d40'
down_revision: Union[str, None] = 'c419a74357fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('last_disable', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('idx_bdm_id_last_disable', 'bank_detail_model', ['id', 'last_disable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bdm_id_last_disable', table_name='bank_detail_model')
    op.drop_column('bank_detail_model', 'last_disable')
    # ### end Alembic commands ###
