"""is_change_amount_allowed

Revision ID: 722a810f30c2
Revises: a799b4f380e4
Create Date: 2024-10-11 17:22:59.109843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722a810f30c2'
down_revision: Union[str, None] = 'a799b4f380e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('is_change_amount_allowed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_change_amount_allowed')
    # ### end Alembic commands ###
