"""added fields for timer

Revision ID: 7913aba8ea25
Revises: c7179db65b0e
Create Date: 2024-07-09 23:00:52.678229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7913aba8ea25'
down_revision: Union[str, None] = 'c7179db65b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.add_column('user_model', sa.Column('transaction_outbound_auto_close_time_s', sa.BigInteger(), nullable=True))
    op.add_column('user_model', sa.Column('withdraw_wallet_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'user_model', 'wallet_model', ['withdraw_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_model', type_='foreignkey')
    op.drop_column('user_model', 'withdraw_wallet_id')
    op.drop_column('user_model', 'transaction_outbound_auto_close_time_s')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    # ### end Alembic commands ###
