"""add geo_settings table

Revision ID: 7c5697472a62
Revises: e8f2d37aeff0
Create Date: 2025-04-24 17:30:42.290880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5697472a62'
down_revision: Union[str, None] = 'e8f2d37aeff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('max_outbound_pending_per_token', sa.Integer(), server_default='10', nullable=False),
        sa.ForeignKeyConstraint(['id'], ['geo.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
        INSERT INTO geo_settings (id)
        SELECT id FROM geo
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_settings')
    # ### end Alembic commands ###
