"""need_check_confirmation

Revision ID: 7f93a62c75b4
Revises: 5fc59e2cc272
Create Date: 2025-06-25 19:35:17.678275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f93a62c75b4'
down_revision: Union[str, None] = '5fc59e2cc272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('need_check_automation', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('geo_settings', sa.Column('req_after_enable_max_pay_in_count', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('geo_settings', sa.Column('req_after_enable_max_pay_in_automation_time', sa.Integer(), server_default='1800', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'req_after_enable_max_pay_in_automation_time')
    op.drop_column('geo_settings', 'req_after_enable_max_pay_in_count')
    op.drop_column('bank_detail_model', 'need_check_automation')
    # ### end Alembic commands ###
