"""appeals timeout_expired

Revision ID: 7f9526b84663
Revises: 6fa4099c5d40
Create Date: 2025-05-28 08:17:12.284851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9526b84663'
down_revision: Union[str, None] = '6fa4099c5d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('timeout_expired', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'timeout_expired')
    # ### end Alembic commands ###
