"""add max_today_amount_used, max_pending_count to bank_detail

Revision ID: 8091b018110d
Revises: fb73f5197c44
Create Date: 2025-02-05 11:05:49.123168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8091b018110d'
down_revision: Union[str, None] = 'fb73f5197c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('max_today_amount_used', sa.BigInteger(), nullable=False, server_default=str(2**32 - 1)))
    op.add_column('bank_detail_model', sa.Column('max_pending_count', sa.BigInteger(), nullable=False, server_default='1'))
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.drop_column('bank_detail_model', 'max_pending_count')
    op.drop_column('bank_detail_model', 'max_today_amount_used')
    # ### end Alembic commands ###
