"""Add second_number to BankDetailModel

Revision ID: 8827f2301d5d
Revises: ce5e9bef8344
Create Date: 2024-08-09 16:17:47.907806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8827f2301d5d'
down_revision: Union[str, None] = 'ce5e9bef8344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('second_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_bank_detail_model_second_number'), 'bank_detail_model', ['second_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_detail_model_second_number'), table_name='bank_detail_model')
    op.drop_column('bank_detail_model', 'second_number')
    # ### end Alembic commands ###
