"""add max_outbound_pending_per_token

Revision ID: 8ecbb09daf72
Revises: 7f93a62c75b4
Create Date: 2025-07-02 19:33:01.234098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ecbb09daf72'
down_revision: Union[str, None] = '7f93a62c75b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('max_outbound_pending_per_token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'max_outbound_pending_per_token')
    # ### end Alembic commands ###
