"""limits in bank_detail

Revision ID: 9116796c4c72
Revises: c71acfd735a8
Create Date: 2024-12-16 12:19:59.520454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9116796c4c72'
down_revision: Union[str, None] = 'c71acfd735a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('fiat_max_inbound', sa.BigInteger(), nullable=False,
                                                 server_default='4294967295'))  # (2**32)-1
    op.add_column('bank_detail_model',
                  sa.Column('fiat_min_inbound', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_detail_model', 'fiat_min_inbound')
    op.drop_column('bank_detail_model', 'fiat_max_inbound')
    # ### end Alembic commands ###
