"""get_back_transaction_time_setting

Revision ID: 93fc9eaa9780
Revises: 9a1118597aa4
Create Date: 2025-05-15 08:43:14.656374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fc9eaa9780'
down_revision: Union[str, None] = '9a1118597aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_settings', sa.Column('get_back_transactions_time_s', sa.Integer(), server_default='7200', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'get_back_transactions_time_s')
    # ### end Alembic commands ###
