"""delete FK in UserBalanceChangeModel

Revision ID: 96451832ccaf
Revises: a6cb6f38c3cb
Create Date: 2025-06-03 19:33:33.549001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96451832ccaf'
down_revision: Union[str, None] = 'a6cb6f38c3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_balance_change_model_user_id_fkey', 'user_balance_change_model', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_balance_change_model_user_id_fkey', 'user_balance_change_model', 'user_model', ['user_id'], ['id'])
    # ### end Alembic commands ###
