"""Change bank_detail_id to base64 string in vip_payer_model

Revision ID: 9b2b796c54a8
Revises: 93fc9eaa9780
Create Date: 2025-05-15 16:30:40.587983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2b796c54a8'
down_revision: Union[str, None] = '93fc9eaa9780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('vip_payer_model_bank_detail_id_fkey', 'vip_payer_model', type_='foreignkey')
    op.alter_column(
        'vip_payer_model',
        'bank_detail_id',
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vip_payer_model', 'bank_detail_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_foreign_key('vip_payer_model_bank_detail_id_fkey', 'vip_payer_model', 'bank_detail_model',
                          ['bank_detail_id'], ['id'])
    # ### end Alembic commands ###
