"""added message fields

Revision ID: 9c063c5dd33f
Revises: b071b9c4f3f5
Create Date: 2024-08-03 11:22:28.476269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c063c5dd33f'
down_revision: Union[str, None] = 'b071b9c4f3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.add_column('message_model', sa.Column('comment', sa.String(length=64), nullable=True))
    op.add_column('message_model', sa.Column('epoch', sa.BigInteger(), nullable=True))
    op.add_column('message_model', sa.Column('device_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_message_model_comment'), 'message_model', ['comment'], unique=False)
    op.create_index(op.f('ix_message_model_device_hash'), 'message_model', ['device_hash'], unique=False)
    op.create_index(op.f('ix_message_model_epoch'), 'message_model', ['epoch'], unique=False)
    op.create_unique_constraint('message_cache', 'message_model', ['amount', 'comment', 'epoch', 'device_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_cache', 'message_model', type_='unique')
    op.drop_index(op.f('ix_message_model_epoch'), table_name='message_model')
    op.drop_index(op.f('ix_message_model_device_hash'), table_name='message_model')
    op.drop_index(op.f('ix_message_model_comment'), table_name='message_model')
    op.drop_column('message_model', 'device_hash')
    op.drop_column('message_model', 'epoch')
    op.drop_column('message_model', 'comment')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
