"""add view_details

Revision ID: 9d494e2cd12e
Revises: 6baeae734e26
Create Date: 2025-03-10 13:46:29.878132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d494e2cd12e'
down_revision: Union[str, None] = '6baeae734e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_matrix', sa.Column('view_details', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_matrix', 'view_details')
    # ### end Alembic commands ###
