"""change bank_detail_id in vip to 64 size and add pgcrypt

Revision ID: 9e6732c4a16e
Revises: 9b2b796c54a8
Create Date: 2025-05-16 20:22:23.308829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6732c4a16e'
down_revision: Union[str, None] = '9b2b796c54a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vip_payer_model', 'bank_detail_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vip_payer_model', 'bank_detail_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
