"""max, min, priority

Revision ID: a799b4f380e4
Revises: dddaa65c1a3b
Create Date: 2024-10-09 20:35:07.172407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'a799b4f380e4'
down_revision: Union[str, None] = 'dddaa65c1a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('fiat_max_inbound', sa.BigInteger(), nullable=True))
    op.add_column('user_model', sa.Column('fiat_min_inbound', sa.BigInteger(), nullable=True))
    op.add_column('user_model', sa.Column('priority_inbound', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    user_model_table = table(
        'user_model',
        column('fiat_max_inbound', sa.BigInteger),
        column('fiat_min_inbound', sa.BigInteger),
        column('priority_inbound', sa.Integer)
    )

    op.execute(
        user_model_table.update().values(
            fiat_max_inbound=(2**32) - 1,
            fiat_min_inbound=0,
            priority_inbound=100
        )
    )

    op.alter_column('user_model', 'fiat_max_inbound', nullable=False)
    op.alter_column('user_model', 'fiat_min_inbound', nullable=False)
    op.alter_column('user_model', 'priority_inbound', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'priority_inbound')
    op.drop_column('user_model', 'fiat_min_inbound')
    op.drop_column('user_model', 'fiat_max_inbound')
    # ### end Alembic commands ###
