"""close_payouts_worker_settings_schema

Revision ID: a84cd2b80173
Revises: f2f39260e210
Create Date: 2025-06-20 08:25:29.655737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a84cd2b80173'
down_revision: Union[str, None] = 'f2f39260e210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close_payouts_worker_settings',
        sa.Column('geo_id', sa.Integer(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('amount_ge', sa.BigInteger(), nullable=True),
        sa.Column('amount_le', sa.BigInteger(), nullable=True),
        sa.Column('type_in', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('type_not_in', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('bank_in', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('bank_not_in', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('last_seconds', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['geo_id'], ['geo.id'], ),
        sa.PrimaryKeyConstraint('geo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('close_payouts_worker_settings')
    # ### end Alembic commands ###
