"""add to traffic

Revision ID: a97a0ff2f369
Revises: 9e6732c4a16e
Create Date: 2025-05-19 18:13:16.993671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97a0ff2f369'
down_revision: Union[str, None] = '9e6732c4a16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_weight_contact_model', sa.Column('outbound_amount_less', sa.BigInteger(), nullable=True))
    op.add_column('traffic_weight_contact_model', sa.Column('outbound_amount_great', sa.BigInteger(), nullable=True))
    op.add_column('traffic_weight_contact_model', sa.Column('outbound_bank_in', sa.String(length=512), nullable=True))
    op.add_column('traffic_weight_contact_model', sa.Column('outbound_bank_not_in', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_weight_contact_model', 'outbound_bank_not_in')
    op.drop_column('traffic_weight_contact_model', 'outbound_bank_in')
    op.drop_column('traffic_weight_contact_model', 'outbound_amount_great')
    op.drop_column('traffic_weight_contact_model', 'outbound_amount_less')
    # ### end Alembic commands ###
