"""Add new fields to AccessMatrix model

Revision ID: ab3e5b2a31ee
Revises: 8827f2301d5d
Create Date: 2024-09-03 13:19:48.187956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3e5b2a31ee'
down_revision: Union[str, None] = '8827f2301d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_matrix', sa.Column('view_search', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('access_matrix', sa.Column('view_compensations', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_external_transaction_model_direction'), 'external_transaction_model', ['direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_transaction_model_direction'), table_name='external_transaction_model')
    op.drop_column('access_matrix', 'view_compensations')
    op.drop_column('access_matrix', 'view_search')
    # ### end Alembic commands ###
