"""added message fields

Revision ID: ac7e0f3791e3
Revises: fcfb5e9ec158
Create Date: 2024-08-03 21:27:54.287647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7e0f3791e3'
down_revision: Union[str, None] = 'fcfb5e9ec158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.drop_index('ix_message_model_external_transaction_id', table_name='message_model')
    op.create_index(op.f('ix_message_model_external_transaction_id'), 'message_model', ['external_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_model_external_transaction_id'), table_name='message_model')
    op.create_index('ix_message_model_external_transaction_id', 'message_model', ['external_transaction_id'], unique=False)
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
