"""add reason

Revision ID: ac9830a2eaac
Revises: b176f8752d74
Create Date: 2025-04-10 11:07:53.149028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9830a2eaac'
down_revision: Union[str, None] = 'b176f8752d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_transaction_model', sa.Column('reason', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_transaction_model', 'reason')
    # ### end Alembic commands ###
