"""transaction final status

Revision ID: adb63412292d
Revises: 8ecbb09daf72
Create Date: 2025-07-03 08:12:13.797054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb63412292d'
down_revision: Union[str, None] = '8ecbb09daf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('auto', 'accept', 'appeal', 'recalc', 'timeout', 'cancel', name='transaction_final_status_enum')
    status_enum.create(op.get_bind())
    op.add_column('external_transaction_model', sa.Column('final_status', status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_transaction_model', 'final_status')
    status_enum = sa.Enum(name='transaction_final_status_enum')
    status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
