"""is_auto_active

Revision ID: af3b54f9f895
Revises: 27c92dbc53a6
Create Date: 2024-12-03 18:41:43.260048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3b54f9f895'
down_revision: Union[str, None] = '27c92dbc53a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('is_auto_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.create_index(op.f('ix_bank_detail_model_is_auto_active'), 'bank_detail_model', ['is_auto_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_detail_model_is_auto_active'), table_name='bank_detail_model')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.drop_column('bank_detail_model', 'is_auto_active')
    # ### end Alembic commands ###
