"""deleted currency in bd

Revision ID: b071b9c4f3f5
Revises: bb0bef5c27b0
Create Date: 2024-07-29 09:41:00.033765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b071b9c4f3f5'
down_revision: Union[str, None] = 'bb0bef5c27b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_detail_model_currency', table_name='bank_detail_model')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.drop_column('bank_detail_model', 'currency')
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.add_column('bank_detail_model', sa.Column('currency', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.create_index('ix_bank_detail_model_currency', 'bank_detail_model', ['currency'], unique=False)
    # ### end Alembic commands ###
