"""upgrade vip

Revision ID: b176f8752d74
Revises: 35e00f3da413
Create Date: 2025-04-07 11:36:13.939963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b176f8752d74'
down_revision: Union[str, None] = '35e00f3da413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'vip_payer_model',
        sa.Column(
            'id',
            sa.String(length=64),
            nullable=True,
            server_default=sa.text("gen_random_uuid()::text")
        )
    )

    op.drop_constraint('vip_payer_model_pkey', 'vip_payer_model', type_='primary')

    op.alter_column('vip_payer_model', 'id', nullable=False)

    op.create_primary_key(
        'vip_payer_model_pkey',
        'vip_payer_model',
        ['id']
    )

    op.create_unique_constraint(
        'uq_vip_payer_triple',
        'vip_payer_model',
        ['payer_id', 'merchant_id', 'bank_detail_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vip_payer_triple', 'vip_payer_model', type_='unique')
    op.drop_constraint('vip_payer_model_pkey', 'vip_payer_model', type_='primary')
    op.drop_column('vip_payer_model', 'id')
    op.create_primary_key(
        'vip_payer_model_pkey',
        'vip_payer_model',
        ['payer_id', 'merchant_id']
    )
    # ### end Alembic commands ###
