"""add view analytics

Revision ID: b3aa7a0e18a6
Revises: 592cf6370803
Create Date: 2025-06-10 17:53:42.470833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa7a0e18a6'
down_revision: Union[str, None] = '592cf6370803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_matrix', sa.Column('view_analytics', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_matrix', 'view_analytics')
    # ### end Alembic commands ###
