"""add eps change amount

Revision ID: b477e0a28314
Revises: 1d03e95164d7
Create Date: 2025-06-12 15:07:16.121856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b477e0a28314'
down_revision: Union[str, None] = '1d03e95164d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('left_eps_change_amount_allowed', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('merchants', sa.Column('right_eps_change_amount_allowed', sa.BigInteger(), server_default='0', nullable=False))
    op.drop_column('merchants', 'is_change_amount_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('is_change_amount_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('merchants', 'right_eps_change_amount_allowed')
    op.drop_column('merchants', 'left_eps_change_amount_allowed')
    # ### end Alembic commands ###
