"""add final_status_timestamp

Revision ID: b5241a440ff4
Revises: 9d494e2cd12e
Create Date: 2025-03-10 14:36:56.242955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5241a440ff4'
down_revision: Union[str, None] = '9d494e2cd12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_transaction_model', sa.Column('final_status_timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_transaction_model', 'final_status_timestamp')
    # ### end Alembic commands ###
