"""add max_inbound_pending_per_token

Revision ID: b7821bd85a43
Revises: adb63412292d
Create Date: 2025-07-03 15:01:49.200480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7821bd85a43'
down_revision: Union[str, None] = 'adb63412292d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('max_inbound_pending_per_token', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('count_pending_inbound', sa.Integer(), server_default='0', nullable=False))
    op.execute("""
            UPDATE teams
            SET count_pending_inbound = sub.pending_count
            FROM (
                SELECT team_id, COUNT(*) AS pending_count
                FROM external_transaction_model
                WHERE status = 'pending'
                  AND direction = 'inbound'
                GROUP BY team_id
            ) AS sub
            WHERE teams.id = sub.team_id
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'count_pending_inbound')
    op.drop_column('teams', 'max_inbound_pending_per_token')
    # ### end Alembic commands ###
