"""add index to detail and final status desc

Revision ID: c419a74357fe
Revises: 4ba4c33a9503
Create Date: 2025-05-27 13:57:01.505049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c419a74357fe'
down_revision: Union[str, None] = '4ba4c33a9503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_etm_bdid_fst_desc',
        'external_transaction_model',
        [
            sa.column('bank_detail_id'),
            sa.column('final_status_timestamp').desc()
        ],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_etm_bdid_fst_desc', table_name='external_transaction_model')
    # ### end Alembic commands ###
