"""/bin/zsh

Revision ID: c7179db65b0e
Revises: 240574d3b8f2
Create Date: 2024-07-05 00:33:26.950207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7179db65b0e'
down_revision: Union[str, None] = '240574d3b8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_transaction_model', sa.Column('transfer_to_team_timestamp', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'tag_model', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_model', type_='unique')
    op.drop_column('external_transaction_model', 'transfer_to_team_timestamp')
    # ### end Alembic commands ###
