"""appeal_offset_id

Revision ID: c71acfd735a8
Revises: af3b54f9f895
Create Date: 2024-12-10 13:08:14.966143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71acfd735a8'
down_revision: Union[str, None] = 'af3b54f9f895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('offset_id', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('external_transaction_model_priority_idx', 'external_transaction_model', ['priority'], unique=False)
    op.drop_column('appeals', 'offset_id')
    # ### end Alembic commands ###
