"""appeal close_timestamp

Revision ID: cbc7a0f76a09
Revises: 7c5697472a62
Create Date: 2025-04-24 20:43:37.225679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc7a0f76a09'
down_revision: Union[str, None] = '7c5697472a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('close_timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'close_timestamp')
    # ### end Alembic commands ###
