"""links in payment_form

Revision ID: cf46f56b9b92
Revises: bf6d49d33c6d
Create Date: 2024-11-24 16:06:17.066600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf46f56b9b92'
down_revision: Union[str, None] = 'bf6d49d33c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_forms', sa.Column('links', sa.JSON(), nullable=True))
    op.drop_column('payment_forms', 'sberpay_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_forms', sa.Column('sberpay_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('payment_forms', 'links')
    # ### end Alembic commands ###
