"""is_autowithdraw_enabled

Revision ID: d05c3ab4dd17
Revises: 79aca8658dcb
Create Date: 2024-11-01 18:25:29.962437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'd05c3ab4dd17'
down_revision: Union[str, None] = '79aca8658dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'geo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('namespaces', 'telegram_bot_secret',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.add_column('user_model', sa.Column('is_autowithdraw_enabled', sa.Boolean(), nullable=True))

    conn.execute(
        text("UPDATE user_model SET is_autowithdraw_enabled = FALSE WHERE role IN ('team', 'merchant', 'agent')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_autowithdraw_enabled')
    op.alter_column('namespaces', 'telegram_bot_secret',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('merchants', 'geo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
