"""add profile_id

Revision ID: d073c686859a
Revises: 865e1d39be65
Create Date: 2025-05-23 11:19:23.353600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd073c686859a'
down_revision: Union[str, None] = '865e1d39be65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('profile_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_bank_detail_model_profile_id'), 'bank_detail_model', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_detail_model_profile_id'), table_name='bank_detail_model')
    op.drop_column('bank_detail_model', 'profile_id')
    # ### end Alembic commands ###
