"""max_transfer_count

Revision ID: e0018a4cca7d
Revises: 167c9a605e84
Create Date: 2025-05-12 20:30:43.871614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0018a4cca7d'
down_revision: Union[str, None] = '167c9a605e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_settings', sa.Column('max_transfer_count', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_settings', 'max_transfer_count')
    # ### end Alembic commands ###
