"""add transfer_from_team_timestamp

Revision ID: e8f2d37aeff0
Revises: 48faf167e2c8
Create Date: 2025-04-22 15:01:23.310404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f2d37aeff0'
down_revision: Union[str, None] = '48faf167e2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_association_model', sa.Column('transfer_from_team_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('idx_transfer_association_timestamp_id', 'transfer_association_model', ['transfer_from_team_timestamp'], unique=False)
    op.create_index('idx_transfer_association_transaction_id', 'transfer_association_model', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transfer_association_transaction_id', table_name='transfer_association_model')
    op.drop_index('idx_transfer_association_timestamp_id', table_name='transfer_association_model')
    op.drop_column('transfer_association_model', 'transfer_from_team_timestamp')
    # ### end Alembic commands ###
