"""upgrade MessageModel

Revision ID: f10fe20234a0
Revises: 8091b018110d
Create Date: 2025-02-11 16:12:48.976010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10fe20234a0'
down_revision: Union[str, None] = '8091b018110d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    op.add_column('message_model', sa.Column('number', sa.String(length=64), nullable=True))
    op.add_column('message_model', sa.Column('bank_detail_number', sa.String(length=1024), nullable=True))
    op.alter_column('message_model', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_message_model_bank_detail_number'), 'message_model', ['bank_detail_number'], unique=False)
    op.create_index(op.f('ix_message_model_number'), 'message_model', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_model_number'), table_name='message_model')
    op.drop_index(op.f('ix_message_model_bank_detail_number'), table_name='message_model')
    op.alter_column('message_model', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('message_model', 'bank_detail_number')
    op.drop_column('message_model', 'number')
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    # ### end Alembic commands ###
