"""add today_amount_used and last_transaction_timestamp to bank_detail

Revision ID: fb73f5197c44
Revises: 0b0592dba5ca
Create Date: 2025-02-03 10:56:41.811822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb73f5197c44'
down_revision: Union[str, None] = '0b0592dba5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_detail_model', sa.Column('last_transaction_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('bank_detail_model', sa.Column('today_amount_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['number', 'bank', 'type', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('bank_detail_model_offset_id_index', table_name='bank_detail_model')
    op.create_index('bank_detail_model_offset_id_index', 'bank_detail_model', ['offset_id'], unique=False)
    op.drop_column('bank_detail_model', 'today_amount_used')
    op.drop_column('bank_detail_model', 'last_transaction_timestamp')
    # ### end Alembic commands ###
