flowchart TD
    %% Входящий трафик (Pay-in)
    subgraph Входящий трафик
        A0[Клиент] -->|Клиент запрашивает пополнение баланса в магазине| B0[Система]
        B0[Система] -->|Система назначает карту для пополнения баланса в фиате| B1[Система]
        B1 -->|Проверка поступления денег: Система проверяет, что деньги поступили на карту трейдера.| C1[Система]
        C1 -->|Списание криптовалюты у трейдера: У трейдера списывается эквивалент в криптовалюте. Система маршрутизирует трафик между трейдерами, учитывая их активность и доступность карт.| D1[Трейдер]
        D1 -->|Списанный эквивалент в криптовалюте зачисляется на виртуальный баланс магазина. Все балансы в системе виртуальные и связаны с общим криптокошельком.| E1[Магазин]
    end

    %% Исходящий трафик (Pay-out)
    subgraph Исходящий трафик
        A2[Клиент] -->|Запрос на вывод средств| B2[Магазин]
        B2 -->|Отправка запроса в систему| C2[Система]
        C2 -->|Команда забирает выплату| D2[Система]
        D2 -->|Перевод денег на карту клиента по реквизитам в выплате| E2[Трейдер]
        E2 -->|Проверка и подтверждение транзакции| F2[Саппорт]
        F2 -->|Обновление балансов - списание у магазина, зачисление у трейдера| G2[Система]
    end

    %% Сущности и взаимодействия
    subgraph Сущности и взаимодействия
        F1[Магазин]
        Z2[Трейдер]
        F3[Клиент]
        F4[Саппорт]
        F5[Система]
    end
